### ISSUE TITLE
Group mode

### ISSUE THREAD

**Issue by fdagner** [mebis-lp/mod_kanban#10]
If the group mode is activated in the settings, but there are (still) no groups in the course, the message "Board is being loaded" appears in continuous loop. A hint would be good, maybe "No groups could be found".

**Comment by sh-csg** [comment]
Can you confirm the linked commit fixes the problem?

**Comment by fdagner** [comment]
Board is now loading 👍

**Comment by PhMemmel** [comment]
Thank you @fdagner for reporting and testing. As there have been some changes during CR, it would be nice if you could test again against latest master branch. Closed as fixed.
